web:
  build: .
  environment:
    WEB_CONCURRENCY: 3
    PW_SELENIUM_DRIVER: selenium

  ports:
    - "10.0.2.49:5000:5000"
  command: python app.py
  volumes:
    - .:/usr/app
  links:
    - selenium

selenium:
  image: selenium/standalone-chrome
  ports:
    - "10.0.2.49:4444:4444"